workflows:
  android-app:
    name: Build Android APK
    instance_type: mac_mini
    environment:
      vars:
        PROJECT_PATH: "android/"
        ANDROID_APP_PATH: "android/app/build/outputs/apk/release/app-release.apk"
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
